services:
  - type: web
    name: catdog-classifier
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app